### ISSUE TITLE
Package request: casa-4.2

### ISSUE THREAD

**Issue by smaret** [Gricad/nix-ciment-channel#13]
I would need `casa-4.2` to reduce some ALMA data. There is already a NIX package for `casa-4.7`, but it's cannot be used for the data on (it's not backward compatible...).

The binaries can be found [on this page](https://svn.cv.nrao.edu/casa/distro/linux/old/casapy-42.2.30986-pipe-1-64b.tar.gz).

**Comment by bzizou** [comment]
Wip...

**Comment by smaret** [comment]
Packaging old `casa` versions is a lot of work, and I'm not completely sure it's worth it. Closing this.
