### ISSUE TITLE
Gildas package: online help isn't working

### ISSUE THREAD

**Issue by smaret** [Gricad/nix-ciment-channel#5]
Online help isn't working in Gildas:

```
% mapping
MAPPING> help uv_compress
E-HELP,  Error opening /nix/store/csgym4qw5d0jnqxmki95cyn4f66c99ss-gildas-20170701_d/doc/hlp/map-help-clean.hlp
E-HELP,  No such file or directory (O/S errno #    2)
```

Gildas expects the help file in the `doc/` directory.  However, the nix package installs it in `share/doc`

```
cd /nix/store/csgym4qw5d0jnqxmki95cyn4f66c99ss-gildas-20170701_d
find . -name map-help-clean.hlp
./share/doc/hlp/map-help-clean.hlp
```

`share/doc` is a standard location, so the problem here is to tell Gildas where to find the documentation files.

**Comment by bzizou** [comment]
OK, will take a look at it asap

**Comment by smaret** [comment]
According to @bardeau, the help directory file is defined with the `gag_doc` Gildas variable, which is indeed pointing to the wrong directory:

```
MAPPING> sic log gag_doc:
gag_doc: = /nix/store/csgym4qw5d0jnqxmki95cyn4f66c99ss-gildas-20170701_d/doc/
```

This variable is defined in `etc/gag.dico.gbl`:

```
gag_doc:        $GAG_ROOT_DIR/doc/                     ! Documentation
```

It should be `$GAG_ROOT_DIR/share/doc/`.

**Comment by bardeau** [comment]
For a multi-user installation, you can modify the file $GAG_PATH/gag.dico.gbl ("global dictionary"), as quoted by @smaret. However, this is not recommended (as this file contains the tunings for the default installation). You have to modify/append the file $GAG_PATH/gag.dico.lcl ("local dictionary") which is intended for such customizations. They will have precedence over the gag.dico.gbl file.
